# Generated by Django 6.0.2 on 2026-02-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('total_attendance', models.PositiveIntegerField(default=0)),
                ('visitors_count', models.PositiveIntegerField(default=0)),
                ('healed_count', models.PositiveIntegerField(default=0)),
                ('follow_up_count', models.PositiveIntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('services', models.ManyToManyField(blank=True, related_name='weekly_summaries', to='attendance.service')),
            ],
            options={
                'ordering': ['-week_start'],
                'unique_together': {('week_start', 'week_end')},
            },
        ),
    ]
