# Generated by Django 6.0.2 on 2026-02-10 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_person_occupation_alter_person_residence'),
        ('followup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('phone', 'Phone Call'), ('visit', 'Home Visit'), ('text', 'SMS'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('other', 'Other')], default='phone', max_length=20)),
                ('outcome', models.CharField(choices=[('successful', 'Successful Contact'), ('unsuccessful', 'Unsuccessful Contact'), ('pending', 'Pending'), ('needs_retry', 'Needs Retry')], default='pending', max_length=20)),
                ('comments', models.TextField(help_text='Details about the conversation and outcome')),
                ('response_notes', models.TextField(blank=True, help_text='How the person responded, any concerns mentioned')),
                ('contact_date', models.DateTimeField(auto_now_add=True)),
                ('follow_up_date', models.DateField(help_text='Date the follow-up was attempted')),
                ('is_completed', models.BooleanField(default=False, help_text='Check if follow-up was successfully completed')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('contacted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup_made', to=settings.AUTH_USER_MODEL)),
                ('followup_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='followup.followupcase')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_records', to='attendance.person')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followup_records', to='attendance.service')),
            ],
            options={
                'ordering': ['-follow_up_date', '-contact_date'],
                'indexes': [models.Index(fields=['person', '-follow_up_date'], name='followup_fo_person__a060c6_idx'), models.Index(fields=['service', '-follow_up_date'], name='followup_fo_service_32ccd0_idx'), models.Index(fields=['is_completed', '-follow_up_date'], name='followup_fo_is_comp_4c85a9_idx')],
            },
        ),
    ]
