# Generated by Django 6.0.2 on 2026-02-06 14:28

from django.db import migrations, models


def migrate_service_types(apps, schema_editor):
    """Map old service types to new ones."""
    Service = apps.get_model("attendance", "Service")
    Service.objects.filter(service_type="sunday").update(service_type="sunday_service")
    Service.objects.filter(service_type="midweek").update(service_type="others")
    Service.objects.filter(service_type="special").update(service_type="others")
    Service.objects.filter(service_type="other").update(service_type="others")


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_person_date_of_birth_person_gender"),
    ]

    operations = [
        migrations.RunPython(migrate_service_types, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="service",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("evangelism", "Evangelism"),
                    ("crusade", "Crusade"),
                    ("prayers", "Prayers"),
                    ("home_fellowship", "Home Fellowship"),
                    ("worship_practice", "Worship Practice"),
                    ("worship_extravaganza", "Worship Extravaganza"),
                    ("saturday_preparations", "Saturday Preparations"),
                    ("sunday_service", "Sunday Service"),
                    ("others", "Others"),
                ],
                default="sunday_service",
                max_length=30,
            ),
        ),
    ]
