# Generated by Django 6.0.2 on 2026-02-06 14:52

from django.db import migrations, models


def migrate_status_to_title(apps, schema_editor):
    """Convert old status (member/visitor) to new title field."""
    Person = apps.get_model("attendance", "Person")
    for person in Person.objects.all():
        if hasattr(person, "status") and person.status == "visitor":
            person.title = "visitor"
        else:
            # member or unknown -> default to brother
            person.title = "brother"
        person.save()


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_update_service_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="title",
            field=models.CharField(
                choices=[
                    ("prophet", "Prophet"),
                    ("senior_deputy_archbishop", "Senior Deputy Archbishop"),
                    ("deputy_archbishop", "Deputy Archbishop"),
                    ("bishop", "Bishop"),
                    ("overseer", "Overseer"),
                    ("senior_pastor", "Senior Pastor"),
                    ("pastor", "Pastor"),
                    ("brother", "Brother"),
                    ("sister", "Sister"),
                    ("visitor", "Visitor"),
                    ("employee", "Employee"),
                ],
                default="brother",
                max_length=30,
            ),
            preserve_default=False,
        ),
        migrations.RunPython(migrate_status_to_title, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="person",
            name="status",
        ),
    ]
