# Generated by Django 6.0.2 on 2026-02-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_person_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='title',
            field=models.CharField(choices=[('prophet', 'Prophet'), ('general_overseer', 'General Overseer'), ('senior_archbishop_emeritus', 'Senior Archbishop Emeritus'), ('senior_archbishop', 'Senior Archbishop'), ('senior_deputy_archbishop', 'Senior Deputy Archbishop'), ('deputy_archbishop', 'Deputy Archbishop'), ('bishop', 'Bishop'), ('overseer', 'Overseer'), ('senior_pastor', 'Senior Pastor'), ('pastor', 'Pastor'), ('sister', 'Sister'), ('brother', 'Brother'), ('visitor', 'Visitor'), ('employee', 'Employee')], default='brother', max_length=35),
        ),
    ]
