# Generated by Django 6.0.2 on 2026-02-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_person_occupation_fellowship_residence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='residence',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
