# Generated by Django 6.0.2 on 2026-02-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_person_occupation_alter_person_residence'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='department',
            field=models.CharField(blank=True, choices=[('music', 'Music'), ('ushering', 'Ushering'), ('prayer', 'Prayer'), ('media', 'Media'), ('children_ministry', 'Children Ministry'), ('youth_ministry', 'Youth Ministry'), ('outreach', 'Outreach'), ('administration', 'Administration'), ('maintenance', 'Maintenance'), ('security', 'Security'), ('hospitality', 'Hospitality'), ('teaching', 'Teaching'), ('none', 'None'), ('other', 'Other')], default='none', max_length=30),
        ),
    ]
