# Generated by Django for fellowship migration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_alter_person_gender'),
    ]

    operations = [
        # Create Fellowship model
        migrations.CreateModel(
            name='Fellowship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, serialize=False)),
                ('description', models.TextField(blank=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Fellowship',
                'verbose_name_plural': 'Fellowships',
                'ordering': ['name'],
            },
        ),
        
        # Add default fellowships
        migrations.RunPython(lambda apps, schema_editor: [
            apps.get_model('attendance', 'Fellowship').objects.update_or_create(
                name=name,
                defaults={'description': f'Default fellowship: {name}'}
            ) for name in [
                "Men's Fellowship",
                "Women's Fellowship", 
                "Youth Fellowship",
                "Children",
                "Choir",
                "Ushering",
                "Prayer",
                "None",
                "Other"
            ]
        ]),
        
        # First make fellowship field nullable
        migrations.AlterField(
            model_name='person',
            name='fellowship',
            field=models.CharField(
                choices=[
                    ('mens_fellowship', 'Mens Fellowship'),
                    ('womens_fellowship', 'Womens Fellowship'),
                    ('youth_fellowship', 'Youth Fellowship'),
                    ('children', 'Children'),
                    ('choir', 'Choir'),
                    ('ushering', 'Ushering'),
                    ('prayer', 'Prayer'),
                    ('none', 'None'),
                    ('other', 'Other')
                ],
                max_length=30,
                blank=True,
                null=True
            ),
        ),
        
        # Clear existing fellowship values
        migrations.RunPython(lambda apps, schema_editor: apps.get_model('attendance', 'Person').objects.all().update(fellowship=None)),
        
        # Alter fellowship field to be a foreign key
        migrations.AlterField(
            model_name='person',
            name='fellowship',
            field=models.ForeignKey(
                'attendance.Fellowship', 
                on_delete=models.SET_NULL, 
                null=True, 
                blank=True,
                related_name='people'
            ),
        ),
    ]
