# Generated by Django 6.0.2 on 2026-04-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_organization_multi_tenancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fellowship',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fellowship',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fellowship',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fellowship',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='fellowship',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
